version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "dart"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dependencies"
      include: "scope"
